In [1]:
import pandas as pd
import numpy as np

# Load raw dataset
df = pd.read_csv("retail_sales_raw.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'retail_sales_raw.csv'

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sanik\OneDrive\Desktop\EXCEL\Rab Tech\Q3_Data_Ingestion_Cleaning\retail_sales_raw.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sanik\\OneDrive\\Desktop\\EXCEL\\Rab Tech\\Q3_Data_Ingestion_Cleaning\\retail_sales_raw.csv'

In [3]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\sanik
['.android', '.angular-config.json', '.arduinoIDE', '.config', '.dotnet', '.eclipse', '.gitconfig', '.h2.server.properties', '.idlerc', '.ipynb_checkpoints', '.ipython', '.m2', '.nuget', '.omnisharp', '.p2', '.templateengine', '.vscode', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Desktop', 'Documents', 'Downloads', 'eclipse', 'eclipse-workspace', 'Favorites', 'git', 'Links', 'Local Settings', 'Music', 'My Documents', 'MyMvcApp', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TM.blf', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TM.blf.cnpf', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{2531e5f3-bb8a-11ef-adb3-282e89cdd515}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'Pictures', 'Postman', 'PrintHood', 'py.txt', 'PyCharmMiscProject', 'PycharmProjects', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'source', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Videos', 'wekafiles']

In [4]:
%cd "C:\Users\sanik\OneDrive\Desktop\EXCEL\Rab Tech\Q3_Data_Ingestion_Cleaning"

C:\Users\sanik\OneDrive\Desktop\EXCEL\Rab Tech\Q3_Data_Ingestion_Cleaning

In [5]:
import os
print(os.listdir())

['prepare_data.py', 'Q3_Data_Cleaning.ipynb', 'retail_sales_raw_10000.csv']

In [7]:
import pandas as pd

df = pd.read_csv("retail_sales_raw_10000.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Dataset loaded successfully!
Rows: 10000
Columns: 21

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [8]:
# Check dataset information before cleaning

print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape:
(10000, 21)

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

Missing Values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Duplicate Rows:
0

In [9]:
# Create a messy copy for cleaning practice

messy_df = df.copy()

# Add missing values
messy_df.loc[10, "Sales"] = np.nan
messy_df.loc[20, "Profit"] = np.nan
messy_df.loc[30, "City"] = np.nan

# Add duplicate records
messy_df = pd.concat(
    [messy_df, messy_df.iloc[[0, 1, 2]]],
    ignore_index=True
)

# Create inconsistent data types
messy_df.loc[40, "Quantity"] = np.nan
messy_df.loc[50, "Discount"] = np.nan

print("Messy dataset created!")
print("Rows:", messy_df.shape[0])
print("Columns:", messy_df.shape[1])

messy_df.head()

Messy dataset created!
Rows: 10003
Columns: 21

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2016-152156,08-11-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2016-138688,12-06-2016,16-06-2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2015-108966,11-10-2015,18-10-2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [10]:
print("Missing Values Before Cleaning:")
print(messy_df.isnull().sum())

print("\nDuplicate Rows Before Cleaning:")
print(messy_df.duplicated().sum())

Missing Values Before Cleaning:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             1
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            1
Quantity         1
Discount         1
Profit           1
dtype: int64

Duplicate Rows Before Cleaning:
3

In [11]:
# Handle missing values

# Numeric columns → fill with median
messy_df["Sales"] = messy_df["Sales"].fillna(messy_df["Sales"].median())
messy_df["Profit"] = messy_df["Profit"].fillna(messy_df["Profit"].median())
messy_df["Quantity"] = messy_df["Quantity"].fillna(messy_df["Quantity"].median())
messy_df["Discount"] = messy_df["Discount"].fillna(0)

# Text column → fill with mode
messy_df["City"] = messy_df["City"].fillna(messy_df["City"].mode()[0])

print("Missing values handled successfully!")
print("\nRemaining missing values:")
print(messy_df.isnull().sum())

Missing values handled successfully!

Remaining missing values:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
# Remove duplicate records

before_duplicates = messy_df.shape[0]

messy_df = messy_df.drop_duplicates()

after_duplicates = messy_df.shape[0]

print("Duplicate records removed:", before_duplicates - after_duplicates)
print("Rows after removing duplicates:", after_duplicates)
print("Remaining duplicates:", messy_df.duplicated().sum())

Duplicate records removed: 3
Rows after removing duplicates: 10000
Remaining duplicates: 0

In [13]:
# Convert date columns to datetime

messy_df["Order Date"] = pd.to_datetime(
    messy_df["Order Date"],
    errors="coerce"
)

messy_df["Ship Date"] = pd.to_datetime(
    messy_df["Ship Date"],
    errors="coerce"
)

# Convert numeric columns to proper numeric type

messy_df["Sales"] = pd.to_numeric(
    messy_df["Sales"],
    errors="coerce"
)

messy_df["Quantity"] = pd.to_numeric(
    messy_df["Quantity"],
    errors="coerce"
)

messy_df["Discount"] = pd.to_numeric(
    messy_df["Discount"],
    errors="coerce"
)

messy_df["Profit"] = pd.to_numeric(
    messy_df["Profit"],
    errors="coerce"
)

print("Data types corrected successfully!\n")
print(messy_df.dtypes)

Data types corrected successfully!

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                float64
Discount                float64
Profit                  float64
dtype: object

In [14]:
# Detect outliers using IQR method

def check_outliers(column):
    Q1 = messy_df[column].quantile(0.25)
    Q3 = messy_df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = messy_df[
        (messy_df[column] < lower_limit) |
        (messy_df[column] > upper_limit)
    ]

    print(column, "outliers:", len(outliers))
    print("Lower limit:", lower_limit)
    print("Upper limit:", upper_limit)
    print()

check_outliers("Sales")
check_outliers("Profit")

Sales outliers: 1166
Lower limit: -271.72124999999994
Upper limit: 498.94874999999996

Profit outliers: 1883
Lower limit: -39.7156875
Upper limit: 70.8118125

In [15]:
# Handle outliers using IQR capping

def cap_outliers(column):
    Q1 = messy_df[column].quantile(0.25)
    Q3 = messy_df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    messy_df[column] = messy_df[column].clip(
        lower_limit,
        upper_limit
    )

# Apply IQR capping
cap_outliers("Sales")
cap_outliers("Profit")

print("Outliers handled successfully!")

Outliers handled successfully!

In [16]:
# Feature Engineering

# Extract Year and Month from Order Date
messy_df["Order Year"] = messy_df["Order Date"].dt.year
messy_df["Order Month"] = messy_df["Order Date"].dt.month

# Calculate Profit Margin
messy_df["Profit Margin (%)"] = np.where(
    messy_df["Sales"] != 0,
    (messy_df["Profit"] / messy_df["Sales"]) * 100,
    0
)

print("Feature engineering completed!")

print("\nNew Columns:")
print(messy_df[["Order Year", "Order Month", "Profit Margin (%)"]].head())

Feature engineering completed!

New Columns:
   Order Year  Order Month  Profit Margin (%)
0      2016.0          8.0          16.000000
1      2016.0          8.0          14.192202
2      2016.0         12.0          47.000000
3      2015.0         11.0          -7.959873
4      2015.0         11.0          11.250000

In [17]:
# Final validation after cleaning

print("===== BEFORE CLEANING =====")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing Values:", df.isnull().sum().sum())
print("Duplicate Rows:", df.duplicated().sum())

print("\n===== AFTER CLEANING =====")
print("Rows:", messy_df.shape[0])
print("Columns:", messy_df.shape[1])
print("Missing Values:", messy_df.isnull().sum().sum())
print("Duplicate Rows:", messy_df.duplicated().sum())

print("\nFinal Columns:")
print(messy_df.columns.tolist())

===== BEFORE CLEANING =====
Rows: 10000
Columns: 21
Missing Values: 0
Duplicate Rows: 0

===== AFTER CLEANING =====
Rows: 10000
Columns: 24
Missing Values: 23965
Duplicate Rows: 0

Final Columns:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Order Year', 'Order Month', 'Profit Margin (%)']

In [18]:
# Export cleaned dataset

messy_df.to_csv("clean_dataset.csv", index=False)

print("Clean dataset exported successfully!")
print("File name: clean_dataset.csv")
print("Final shape:", messy_df.shape)

Clean dataset exported successfully!
File name: clean_dataset.csv
Final shape: (10000, 24)

In [19]:
# Display final cleaned dataset

clean_df = pd.read_csv("clean_dataset.csv")

print("Clean CSV loaded successfully!")
print("Rows:", clean_df.shape[0])
print("Columns:", clean_df.shape[1])
print("Missing values:", clean_df.isnull().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())

clean_df.head()

Clean CSV loaded successfully!
Rows: 10000
Columns: 24
Missing values: 23965
Duplicate rows: 0

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Profit Margin (%)
0,1,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96000,2.0,0.00,41.913600,2016.0,8.0,16.000000
1,2,CA-2016-152156,2016-08-11,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",498.94875,3.0,0.00,70.811813,2016.0,8.0,14.192202
2,3,CA-2016-138688,2016-12-06,NaN,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62000,2.0,0.00,6.871400,2016.0,12.0,47.000000
3,4,US-2015-108966,2015-11-10,NaN,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,498.94875,5.0,0.45,-39.715688,2015.0,11.0,-7.959873
4,5,US-2015-108966,2015-11-10,NaN,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.36800,2.0,0.20,2.516400,2015.0,11.0,11.250000